/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppManualRouteImport } from './routes/app.manual'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBudgetsRouteImport } from './routes/app.budgets'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPaidRiskRouteImport } from './routes/api/paid/risk'
import { Route as ApiPaidReportsRouteImport } from './routes/api/paid/reports'
import { Route as ApiPaidInsightRouteImport } from './routes/api/paid/insight'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicPaidRiskRouteImport } from './routes/api/public/paid/risk'
import { Route as ApiPublicPaidReportsRouteImport } from './routes/api/public/paid/reports'
import { Route as ApiPublicPaidInsightRouteImport } from './routes/api/public/paid/insight'
import { Route as ApiPublicHooksX402RunnerRouteImport } from './routes/api/public/hooks/x402-runner'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaidRiskRoute = ApiPaidRiskRouteImport.update({
  id: '/api/paid/risk',
  path: '/api/paid/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaidReportsRoute = ApiPaidReportsRouteImport.update({
  id: '/api/paid/reports',
  path: '/api/paid/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaidInsightRoute = ApiPaidInsightRouteImport.update({
  id: '/api/paid/insight',
  path: '/api/paid/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaidRiskRoute = ApiPublicPaidRiskRouteImport.update({
  id: '/api/public/paid/risk',
  path: '/api/public/paid/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaidReportsRoute = ApiPublicPaidReportsRouteImport.update({
  id: '/api/public/paid/reports',
  path: '/api/public/paid/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaidInsightRoute = ApiPublicPaidInsightRouteImport.update({
  id: '/api/public/paid/insight',
  path: '/api/public/paid/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksX402RunnerRoute =
  ApiPublicHooksX402RunnerRouteImport.update({
    id: '/api/public/hooks/x402-runner',
    path: '/api/public/hooks/x402-runner',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/chat': typeof AppChatRoute
  '/app/docs': typeof AppDocsRoute
  '/app/manual': typeof AppManualRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paid/insight': typeof ApiPaidInsightRoute
  '/api/paid/reports': typeof ApiPaidReportsRoute
  '/api/paid/risk': typeof ApiPaidRiskRoute
  '/api/public/hooks/x402-runner': typeof ApiPublicHooksX402RunnerRoute
  '/api/public/paid/insight': typeof ApiPublicPaidInsightRoute
  '/api/public/paid/reports': typeof ApiPublicPaidReportsRoute
  '/api/public/paid/risk': typeof ApiPublicPaidRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/chat': typeof AppChatRoute
  '/app/docs': typeof AppDocsRoute
  '/app/manual': typeof AppManualRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paid/insight': typeof ApiPaidInsightRoute
  '/api/paid/reports': typeof ApiPaidReportsRoute
  '/api/paid/risk': typeof ApiPaidRiskRoute
  '/api/public/hooks/x402-runner': typeof ApiPublicHooksX402RunnerRoute
  '/api/public/paid/insight': typeof ApiPublicPaidInsightRoute
  '/api/public/paid/reports': typeof ApiPublicPaidReportsRoute
  '/api/public/paid/risk': typeof ApiPublicPaidRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/chat': typeof AppChatRoute
  '/app/docs': typeof AppDocsRoute
  '/app/manual': typeof AppManualRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paid/insight': typeof ApiPaidInsightRoute
  '/api/paid/reports': typeof ApiPaidReportsRoute
  '/api/paid/risk': typeof ApiPaidRiskRoute
  '/api/public/hooks/x402-runner': typeof ApiPublicHooksX402RunnerRoute
  '/api/public/paid/insight': typeof ApiPublicPaidInsightRoute
  '/api/public/paid/reports': typeof ApiPublicPaidReportsRoute
  '/api/public/paid/risk': typeof ApiPublicPaidRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/app/budgets'
    | '/app/chat'
    | '/app/docs'
    | '/app/manual'
    | '/app/planner'
    | '/app/portfolio'
    | '/app/reports'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paid/insight'
    | '/api/paid/reports'
    | '/api/paid/risk'
    | '/api/public/hooks/x402-runner'
    | '/api/public/paid/insight'
    | '/api/public/paid/reports'
    | '/api/public/paid/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/app/budgets'
    | '/app/chat'
    | '/app/docs'
    | '/app/manual'
    | '/app/planner'
    | '/app/portfolio'
    | '/app/reports'
    | '/app'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paid/insight'
    | '/api/paid/reports'
    | '/api/paid/risk'
    | '/api/public/hooks/x402-runner'
    | '/api/public/paid/insight'
    | '/api/public/paid/reports'
    | '/api/public/paid/risk'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/app/budgets'
    | '/app/chat'
    | '/app/docs'
    | '/app/manual'
    | '/app/planner'
    | '/app/portfolio'
    | '/app/reports'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paid/insight'
    | '/api/paid/reports'
    | '/api/paid/risk'
    | '/api/public/hooks/x402-runner'
    | '/api/public/paid/insight'
    | '/api/public/paid/reports'
    | '/api/public/paid/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPaidInsightRoute: typeof ApiPaidInsightRoute
  ApiPaidReportsRoute: typeof ApiPaidReportsRoute
  ApiPaidRiskRoute: typeof ApiPaidRiskRoute
  ApiPublicHooksX402RunnerRoute: typeof ApiPublicHooksX402RunnerRoute
  ApiPublicPaidInsightRoute: typeof ApiPublicPaidInsightRoute
  ApiPublicPaidReportsRoute: typeof ApiPublicPaidReportsRoute
  ApiPublicPaidRiskRoute: typeof ApiPublicPaidRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manual': {
      id: '/app/manual'
      path: '/manual'
      fullPath: '/app/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budgets': {
      id: '/app/budgets'
      path: '/budgets'
      fullPath: '/app/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paid/risk': {
      id: '/api/paid/risk'
      path: '/api/paid/risk'
      fullPath: '/api/paid/risk'
      preLoaderRoute: typeof ApiPaidRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paid/reports': {
      id: '/api/paid/reports'
      path: '/api/paid/reports'
      fullPath: '/api/paid/reports'
      preLoaderRoute: typeof ApiPaidReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paid/insight': {
      id: '/api/paid/insight'
      path: '/api/paid/insight'
      fullPath: '/api/paid/insight'
      preLoaderRoute: typeof ApiPaidInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paid/risk': {
      id: '/api/public/paid/risk'
      path: '/api/public/paid/risk'
      fullPath: '/api/public/paid/risk'
      preLoaderRoute: typeof ApiPublicPaidRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paid/reports': {
      id: '/api/public/paid/reports'
      path: '/api/public/paid/reports'
      fullPath: '/api/public/paid/reports'
      preLoaderRoute: typeof ApiPublicPaidReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paid/insight': {
      id: '/api/public/paid/insight'
      path: '/api/public/paid/insight'
      fullPath: '/api/public/paid/insight'
      preLoaderRoute: typeof ApiPublicPaidInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/x402-runner': {
      id: '/api/public/hooks/x402-runner'
      path: '/api/public/hooks/x402-runner'
      fullPath: '/api/public/hooks/x402-runner'
      preLoaderRoute: typeof ApiPublicHooksX402RunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppChatRoute: typeof AppChatRoute
  AppDocsRoute: typeof AppDocsRoute
  AppManualRoute: typeof AppManualRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetsRoute: AppBudgetsRoute,
  AppChatRoute: AppChatRoute,
  AppDocsRoute: AppDocsRoute,
  AppManualRoute: AppManualRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPaidInsightRoute: ApiPaidInsightRoute,
  ApiPaidReportsRoute: ApiPaidReportsRoute,
  ApiPaidRiskRoute: ApiPaidRiskRoute,
  ApiPublicHooksX402RunnerRoute: ApiPublicHooksX402RunnerRoute,
  ApiPublicPaidInsightRoute: ApiPublicPaidInsightRoute,
  ApiPublicPaidReportsRoute: ApiPublicPaidReportsRoute,
  ApiPublicPaidRiskRoute: ApiPublicPaidRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
